# Setup
title: Luis on the Keyboard
tagline: Solving problems. Building things.
url: https://luisonthekeyboard.github.io/
paginate: 1
baseurl: ""

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


# Specify the author for blog posts
author:
  name: Luís Rodrigues Soares
  url: https://luisonthekeyboard.com

# Navbar page list
nav:
  - title: About
    url: /about
