# Setup
title: Luís on the Keyboard
tagline: Classic, but modern.
url: https://luisonthekeyboard.github.io/

# Gems
plugins:
  - jekyll-gist
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - archive.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: Luís Rodrigues Soares
  url: https://luisonthekeyboard.github.io

# Navbar page list
nav:
  - title: About
    url: /about
