title: Luís on the Keyboard
tagline: Classic, but modern.
url: https://luisonthekeyboard.github.io/
timezone: Europe/Berlin

plugins:
  - jekyll-seo-tag

exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - archive.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Luís Rodrigues Soares
  url: https://luisonthekeyboard.github.io

nav:
  - title: About
    url: /about
